- name: Install diskimage-builder
  shell: sudo pip3 install diskimage-builder

- name: Create Ubuntu Images
  shell:
    cmd: |
      mkdir -p /home/zuul/dib
      cd /home/zuul/dib

      export DIB_DEV_USER_USERNAME=stack
      export DIB_DEV_USER_PASSWORD=cr0wBar!
      export DIB_DEV_USER_PWDLESS_SUDO=Yes

      sudo apt install debootstrap -y

      disk-image-create ubuntu-minimal baremetal simple-init grub2 devuser openssh-server -o ubuntu-partition
      disk-image-create ubuntu-minimal vm block-device-efi simple-init devuser openssh-server -o ubuntu-wholedisk-uefi

- name: Upload images to glance
  shell:
    cmd: |
      /bin/bash -c """
      source /opt/stack/devstack/openrc admin
      cd /home/zuul/dib
      openstack image create --public --disk-format aki --container-format aki --file ubuntu-partition.vmlinuz ubuntu-partition-kernel
      openstack image create --public --disk-format ari --container-format ari --file ubuntu-partition.initrd ubuntu-partition-ramdisk
      KERNEL_UUID=$(openstack image list | grep ubuntu-partition-kernel | awk '{print $2}')
      RAMDISK_UUID=$(openstack image list | grep ubuntu-partition-ramdisk | awk '{print $2}')
      openstack image create --public --disk-format qcow2 --container-format bare --property kernel_id=$KERNEL_UUID --property ramdisk_id=$RAMDISK_UUID --file ubuntu-partition.qcow2 ubuntu-partition
      openstack image create --public --disk-format qcow2 --container-format bare --file ubuntu-wholedisk-uefi.qcow2 ubuntu-wholedisk-uefi
      """