- name: Clone MoltenIron
  become_user: stack
  shell:
    cmd: |
      sudo chmod -R 777 /opt
      cd /opt/stack
      git clone https://opendev.org/openstack/molteniron
      cd molteniron
      sudo pip3 install .

- name: Create conf.yaml
  become_user: stack
  shell:
    cmd: |
      cd /opt/stack/molteniron
      mkdir -p /opt/stack/logs/molteniron
      echo "mi_port: 5656" >> conf.yaml
      echo "serverIP: 172.16.97.20" >> conf.yaml
      echo "maxTime: 120000" >> conf.yaml
      echo "logdir: /opt/stack/logs/molteniron" >> conf.yaml
      echo "maxLogDays: 7" >> conf.yaml
      echo "sqlUser: molteniron" >> conf.yaml
      echo "sqlPass: password" >> conf.yaml

- name: Start moltenirond-helper
  become_user: stack
  shell: sudo moltenirond-helper -c /opt/stack/molteniron start

- name: Checkout BareMetal
  become_user: stack
  shell:
    cmd: |
      while :
      do
        molteniron -c /opt/stack/molteniron allocate {{ reserved_by }} 1 {{ build_label }} > /tmp/molteniron-checkout.json
        rc=$?
        if [ $rc = 0 ]; then
          break
        fi
      echo "Waiting for BareMetal to Become Available"
      sleep 60
      done

- name: Show molteniron-checkout.json
  become_user: stack
  shell: "cat /tmp/molteniron-checkout.json"

- name: create hardware_info file
  become_user: stack
  shell:
    cmd: |
      mkdir -p /opt/stack/devstack/files
      bmcIp=$(cat /tmp/molteniron-checkout.json | cut -d' ' -f23 | cut -d'"' -f2)
      macAddr=$(cat /tmp/molteniron-checkout.json | cut -d' ' -f13 | cut -d'"' -f2 | cut -d'\' -f1)
      bmcUser=$(cat /tmp/molteniron-checkout.json | cut -d' ' -f9 | cut -d'"' -f2 | cut -d'\' -f1)
      bmcPass=$(cat /tmp/molteniron-checkout.json | cut -d' ' -f11 | cut -d'"' -f2 | cut -d'\' -f1)
      echo "$bmcIp $macAddr $bmcUser $bmcPass /redfish/v1/Systems/System.Embedded.1 False" > /opt/stack/devstack/files/hardware_informo

- name: Show hardware_info
  become_user: stack
  shell: "cat /opt/stack/devstack/files/hardware_informo"