- name: Checkin BareMetal
  become_user: stack
  shell:
    executable: /bin/bash
    cmd: |
      sudo pip3 install 'PyYAML==5.4.1'
      molteniron -c /opt/stack/molteniron release {{ zuul.build[:7] }}