- hosts: all
  roles:
    - fetch-output
    - merge-output-to-logs

- hosts: all
  ignore_errors: yes
  roles:
    - remove-build-sshkey

- hosts: localhost
  gather_facts: False
  roles:
    - generate-zuul-manifest
    - role: upload-logs
      zuul_log_url: "http://172.16.97.20:8000"
    - add-wait