- hosts: all
  roles:
    - fetch-output
    - merge-output-to-logs

- hosts: all
  ignore_errors: yes
  roles:
    - remove-build-sshkey

- hosts: localhost
  gather_facts: False
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - generate-zuul-manifest
    
- hosts: 172.16.97.20
  gather_facts: False
  roles:
    - role: upload-logs
      zuul_log_url: "https://stash.dellemc-community.org/logs"
      zuul_log_compress: false