- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_path_shard_build: true
    - log-inventory
    - ensure-output-dirs

- hosts: all
  pre_tasks:
    - name: Start zuul console daemon
      zuul_console:
    - name: Gather network facts
      setup:
        gather_subset: 'network'
    - name: Check growroot logs
      become: yes
      ignore_errors: yes
      command: journalctl -u growroot
  roles:
    - configure-resolvconf
    - ensure-output-dirs

- hosts: all
  roles:
    - prepare-workspace
    - molteniron-checkout