- name: testo
  hosts: all
  tasks:
  - name: whoami
    shell: whoami
  - name: pwd
    shell: pwd
  - name: ping
    shell: ping -c 10 google.com
  - name: update
    shell: sudo apt update -y; sudo apt upgrade -y
  - name: branch
    shell: echo {{ zuul.branch }}
  - name: clone
    shell: mv src/opendev.org/opendev/ci-sandbox .; cd ci-sandbox; git --no-pager log
  - name: make logs
    shell: echo yo > zuul-output/logs/yo.txt
