- name: Run devstack
  shell:
    executable: /bin/bash
    cmd: |
      if [[ {{ zuul.branch }} == stable/train ]]; then
        rm -rf /opt/stack/tempest
      fi
      ./stack.sh 2>&1
      rc=$?
      echo "*** FINISHED ***"
      exit $rc
  args:
    chdir: "{{devstack_base_dir}}/devstack"
  become: true
  become_user: stack
